### ISSUE TITLE
Question Gathering

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ICT-2101-P2-10#25]
Gather Questions for Client Meeting
Insert questions inside below:
https://docs.google.com/document/d/1wnEVL3r82wOkMFiGPNLtVegwnb8BfW5_Uik-HjQ1j8o/edit

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/191992000-5ca98853-f0f6-4f7a-a494-42341abd278e.png)
