### ISSUE TITLE
Requirements Finalization

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/ICT-2101-P2-10#27]
Finalize the user requirements and insert them in the report below:
https://docs.google.com/document/d/1xDyUC5FGobB9g-r1f9FWs7PFDyOdS7xHSwx-XUp41u8/edit#heading=h.gjdgxs

**Comment by timothxy** [comment]
![Image](https://user-images.githubusercontent.com/92201555/191992265-d3a5b607-2e80-4b76-af6c-ad6acf7bd11d.png)
